version: '3.8'
services:
  mongo:
    container_name: "mongodb"
    image: mongo:4.4
    hostname: mongodb
    restart: always
    volumes:
      - ./data/mongodb/mongod.conf:/etc/mongod.conf
      - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/mongodb/data/db/:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=development
      - MONGO_INITDB_USER=mongodb
      - MONGO_INITDB_PWD=mongodb
    ports:
      - 27017:27017
    networks:
      - shared-network
    command: [ "-f", "/etc/mongod.conf" ]

  api:
    build: ./server-side
    restart: unless-stopped
    ports:
      - "2400:2400"
    environment:
      DB_URL: mongodb+srv://alisia:12341234@cluster0.ko7bqp4.mongodb.net/?retryWrites=true&w=majority
      clientID: "8f80d399a407f5416b92"
      clientSecret: "ed10add7a1124c625658071dc442a5773451ac76"
    networks:
      - shared-network
    depends_on:
      - mongo

  client:
    build:
      context: ./client-side
    ports:
      - "3000:3000"
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
